// src/adapters/offline.ts
//
// OfflineAdapter — a deterministic, ZERO-NETWORK stub model adapter.
//
// Purpose: let the Conductor pipeline run with NO API keys (CI, demos,
// dogfooding). Every invoke() returns a fixed, valid response for its
// operation so a card can walk discovered → planned → approved → building →
// verifying → shipped → archived without ever touching a real LLM.
//
// IMPORTANT: this adapter does NOT do real engineering. It is a STUB. The
// `implement` op emits a placeholder file (a fresh, collision-safe path under
// conductor-offline/) rather than a real code change; the read-classification
// ops (review/verify) always return the "happy path" verdict so the walk
// advances. Use it only to exercise the pipeline mechanics, never to produce
// real work.
//
// Determinism: same input → same output. No Date, no Math.random, no network,
// no filesystem reads. capabilities().tools === false so every op takes its
// single-invoke (tool-less) path — this both keeps output deterministic and
// avoids the agentic read-loop (which would re-invoke this adapter).

import type { ModelAdapter, AdapterCapabilities } from './adapter.js';
import type { OperationRequest, OperationResponse } from '../engine/operation.js';

/** Build the per-op response TEXT the corresponding op parses. Each branch is
 *  matched to the exact contract the op enforces (see src/engine/ops/*.ts). */
function offlineText(operation: string): string {
  switch (operation) {
    // analyze.ts: returns raw text; persisted as the analysis artifact and
    // handed to plan in-memory. Any non-empty markdown works.
    case 'analyze':
      return [
        '## Validation',
        'OFFLINE STUB — no real analysis was performed (deterministic adapter).',
        '',
        '## Root Cause',
        'N/A (offline stub).',
        '',
        '## Blast Radius',
        'A single placeholder file under conductor-offline/.',
        '',
        '## Approach',
        'Emit a deterministic placeholder file so the pipeline can advance.',
      ].join('\n');

    // plan.ts: raw text. Must contain a step the walker/implement can resolve;
    // the lifecycle uses step "1.1" (the operator passes --step, but we mirror
    // the same id here so the artifact + diff agree).
    case 'plan':
      return [
        '### Resolved decisions from analysis',
        '- Emit a placeholder file at conductor-offline/step-1.1.md (offline stub).',
        '',
        '### Step 1.1 — offline placeholder',
        'WHAT: create conductor-offline/step-1.1.md',
        'HOW: write a deterministic placeholder marker file',
        'WHY: lets the keyless pipeline advance end-to-end',
        'RISK: none (fresh file, no existing code touched)',
        'VERIFY: the configured verify_command is classified PASS by the stub',
        'ROLLBACK: delete conductor-offline/step-1.1.md',
      ].join('\n');

    // review.ts: parseJsonResponse → { decision, reasoning, changes_required }.
    // decision MUST be one of APPROVED|NEEDS-CHANGES|NEEDS-INFO; APPROVED makes
    // the walker advance planned → approved.
    case 'review':
      return JSON.stringify({
        decision: 'APPROVED',
        reasoning: 'Offline stub auto-approves so the keyless pipeline advances.',
        changes_required: [],
      });

    // implement.ts: parseJsonResponse → Diff { step, commit_type, commit_subject,
    // files:[{path, action, content}], notes }. commit_type MUST be in
    // COMMIT_TYPES. We CREATE one fresh file (action 'create' never collides
    // because the path is unique to this stub) — never 'modify' (the adapter
    // can't read existing files to reproduce them).
    case 'implement':
      return JSON.stringify({
        step: '1.1',
        commit_type: 'chore',
        commit_subject: 'add offline placeholder for step 1.1',
        files: [
          {
            path: 'conductor-offline/step-1.1.md',
            action: 'create',
            content:
              '# Offline placeholder (step 1.1)\n\n' +
              'Generated by the deterministic OfflineAdapter. This is NOT a real\n' +
              'implementation — it exists only so the keyless pipeline can advance.\n',
          },
        ],
        notes: 'Offline stub created a placeholder file; no real engineering performed.',
      });

    // verify.ts: the op runs the real verify_command itself and asks the model
    // ONLY to classify the captured output. parseJsonResponse → { outcome,
    // summary, failures }. outcome MUST be PASS|FAIL|SKIP; PASS advances the
    // walker building → verifying.
    case 'verify':
      return JSON.stringify({
        outcome: 'PASS',
        summary: 'Offline stub classifies the verify output as PASS.',
        failures: [],
      });

    // resolve.ts: parseJsonResponse → { summary }. files_changed is derived
    // from git by the op, so only the summary is needed from the model.
    case 'resolve':
      return JSON.stringify({
        summary:
          'Shipped via the offline stub: a placeholder file was created so the ' +
          'keyless pipeline could walk the card end-to-end. No real change.',
      });

    // order.ts: parseJsonResponse → { entries }. The op validates that every
    // entry references a known card id; an empty list is the only universally
    // safe deterministic output (it can never reference an unknown id).
    case 'order':
      return JSON.stringify({ entries: [] });

    // discover.ts: parseJsonResponse → { items }. Empty = "nothing to file".
    case 'discover':
      return JSON.stringify({ items: [] });

    // exercise.ts: exercise_map → { scenarios }, exercise_run → { findings }.
    // Returning BOTH keys (each empty) satisfies whichever sub-op is invoked.
    case 'exercise':
    case 'exercise_map':
    case 'exercise_run':
      return JSON.stringify({ scenarios: [], findings: [] });

    // chat.ts / chat_agent.ts: with tools:false, chat_agent takes its fallback
    // path and returns resp.text.trim() as the reply. Plain text is correct.
    case 'chat':
    case 'chat_agent':
      return 'Offline stub: chat is unavailable without an API key.';

    // scan.ts makes NO adapter call (deterministic, filesystem-only) and
    // notebook.ts makes NO adapter call — they never reach here. Any other
    // op gets a deterministic non-empty string so nothing throws.
    default:
      return `OFFLINE ${operation}: deterministic stub response (no real work).`;
  }
}

export class OfflineAdapter implements ModelAdapter {
  readonly id = 'offline';

  async invoke(req: OperationRequest): Promise<OperationResponse> {
    const text = offlineText(req.operation);
    // Deterministic, fixed token accounting (no input-length dependence, so the
    // response is byte-identical regardless of prompt size).
    return {
      text,
      toolCalls: [],
      inputTokens: 0,
      outputTokens: 0,
      totalTokens: 0,
      model: req.model,
    };
  }

  capabilities(): AdapterCapabilities {
    return {
      // tools:false → ops use their single-invoke path (no agentic read loop),
      // keeping output deterministic and avoiding adapter re-entry.
      tools: false,
      contextWindowTokens: 200_000,
      streaming: false,
      costTier: 'free',
      supportsExtendedThinking: false,
      supportsPromptCaching: false,
    };
  }

  estimateCost(): { tokens: number; dollars: number } {
    return { tokens: 0, dollars: 0 };
  }
}
