// src/cli/commands/init.ts
//
// `conductor init` — scaffold .conductor/ in the current repo.
//
// Creates the three-tier memory layout (Tier 1: state.md / ordering.md /
// journal.md; Tier 2: cards/ archive/ decisions/ phases/ exercise/;
// Tier 3 SQLite + transports are created lazily by the daemon, not here).
// Idempotent: re-runnable safely; never overwrites existing config.

import { mkdir, writeFile, access } from 'node:fs/promises';
import { join } from 'node:path';
import type { Command } from 'commander';

const SUBDIRS = [
  'cards',
  'archive',
  'archive/cards',
  'archive/implemented',
  'archive/notebooks',
  'archive/exercise',
  'decisions',
  'phases',
  'exercise',
  'snapshots',
  'runs',
];

const DEFAULT_CONFIG = `# .conductor/config.yaml — Conductor project configuration
routing:
  default: claude-sonnet-4-6
  functions:
    analyze: claude-opus-4-7
    plan: claude-opus-4-7
autonomy:
  default: assist
  transitions:
    discovered_to_planned:    auto
    planned_to_approved:      assist
    approved_to_building:     manual
    building_to_verifying:    auto
    verifying_to_shipped:     assist
    shipped_to_archived:      manual
`;

const DEFAULT_STATE = `# Conductor STATE

Current phase: unassigned
Current card: (none)
Next action: file the first card with \`conductor card new <slug>\`
Recent decisions: (none yet)
`;

const DEFAULT_ORDERING = `# Ordering

(Generated by \`conductor order\`. No active cards yet.)
`;

const DEFAULT_JOURNAL = `# Journal

(One line per session, appended at session end.)
`;

export interface InitArgs {
  cwd: string;
}

export async function runInit(args: InitArgs): Promise<void> {
  const root = join(args.cwd, '.conductor');
  await mkdir(root, { recursive: true });
  for (const sub of SUBDIRS) {
    await mkdir(join(root, sub), { recursive: true });
  }
  await writeIfMissing(join(root, 'config.yaml'), DEFAULT_CONFIG);
  await writeIfMissing(join(root, 'state.md'), DEFAULT_STATE);
  await writeIfMissing(join(root, 'ordering.md'), DEFAULT_ORDERING);
  await writeIfMissing(join(root, 'journal.md'), DEFAULT_JOURNAL);
}

async function writeIfMissing(path: string, content: string): Promise<void> {
  try {
    await access(path);
    return;
  } catch {
    /* not present — write it */
  }
  await writeFile(path, content, 'utf8');
}

export function attachInit(program: Command): void {
  program
    .command('init')
    .description('Initialize Conductor in the current repo (.conductor/ layout + defaults)')
    .action(async () => {
      await runInit({ cwd: process.cwd() });
      // eslint-disable-next-line no-console
      console.log('Conductor initialized. .conductor/ scaffold ready.');
    });
}
