// src/cli/commands/init.ts
//
// `conductor init [--provider <name>]` — scaffold .conductor/ in the current repo.
//
// Creates the three-tier memory layout (Tier 1: state.md / ordering.md /
// journal.md; Tier 2: cards/ archive/ decisions/ phases/ exercise/;
// Tier 3 SQLite + transports are created lazily by the daemon, not here).
// Idempotent: re-runnable safely; never overwrites existing config.
//
// --provider <name> picks the example config to install. Without it,
// installs an embedded multi-provider default that routes to claude/openai/
// gemini/local. With it, copies examples/with-<name>/.conductor/config.yaml.

import { mkdir, writeFile, access, readFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { Command } from 'commander';

const SUBDIRS = [
  'cards',
  'archive',
  'archive/cards',
  'archive/implemented',
  'archive/notebooks',
  'archive/exercise',
  'decisions',
  'phases',
  'exercise',
  'snapshots',
  'runs',
];

const DEFAULT_CONFIG = `# .conductor/config.yaml — Conductor project configuration
#
# Routing precedence (lowest → highest):
#   1. routing.default                          (this file)
#   2. routing.functions.<op>                   (this file)
#   3. card frontmatter model_overrides.<op>    (per-card)
#
# Provider is resolved by model id prefix:
#   claude-*                  → Anthropic API (ANTHROPIC_API_KEY)
#   claude-sub:*              → Claude Code subscription (claude login)
#   gpt-*, codex*, o1/o3/o4*  → OpenAI
#   gemini-*                  → Google
#   openrouter:*              → OpenRouter
#   local:*, ollama:*, vllm:*, lmstudio:* → OpenAI-compat local endpoint
routing:
  default: claude-sonnet-4-6
  functions:
    analyze:      claude-opus-4-7        # heavy reasoning
    plan:         claude-opus-4-7
    review:       claude-opus-4-7        # adversarial; want best
    implement:    gpt-5                  # rapid impl
    verify:       claude-haiku-4-5       # cheap validation
    scan:         gemini-2.5-pro         # large context
    discover:     gemini-2.5-pro
    order:        claude-haiku-4-5
    detect_drift: local:llama-3.3-70b    # deterministic; regex+git
# Phase 30.7 / Relay #60: spectrum-shape autonomy config. Project default is
# one of assist (every decision surfaces to operator) | hybrid (threshold-gated
# auto-execute) | autonomous (executor never surfaces). Per-card override via
# card frontmatter autonomy field (also accepts 'inherit' to defer to this
# default). Legacy transitions per-edge block (and legacy default values
# escort | auto | critical) still accepted on input with a deprecation warning;
# they're mapped to spectrum at load time.
autonomy:
  default: hybrid
  hybrid_confidence_threshold: 0.7
verify_command: npm test
`;

const DEFAULT_STATE = `# Conductor STATE

Current phase: unassigned
Current card: (none)
Next action: file the first card with \`conductor card new <slug>\`
Recent decisions: (none yet)
`;

const DEFAULT_ORDERING = `# Ordering

(Generated by \`conductor order\`. No active cards yet.)
`;

const DEFAULT_JOURNAL = `# Journal

(One line per session, appended at session end.)
`;

// Sentinel-fenced block written to the user's project .gitignore so daemon-
// written runtime artifacts (auth bearer token, ephemeral endpoint URLs, run
// logs) are ignored from the moment `conductor init` completes. The sentinel
// header is the idempotency gate — re-running init detects this line and
// skips re-adding the block. Users can edit/remove individual lines inside
// the block without breaking idempotency.
const GITIGNORE_SENTINEL_HEADER =
  '# --- conductor managed artifacts (added by `conductor init`) ---';
const GITIGNORE_SENTINEL_FOOTER = '# --- /conductor ---';
const GITIGNORE_BLOCK = [
  GITIGNORE_SENTINEL_HEADER,
  '.conductor/auth.token',
  '.conductor/daemon.pid',
  '.conductor/daemon.endpoint',
  '.conductor/mcp.endpoint',
  '.conductor/runs/',
  '.conductor/snapshots/',
  GITIGNORE_SENTINEL_FOOTER,
].join('\n');

async function ensureGitignoreBlock(
  repo: string,
): Promise<'created' | 'appended' | 'unchanged'> {
  const path = join(repo, '.gitignore');
  let existed = true;
  let existing = '';
  try {
    existing = await readFile(path, 'utf8');
  } catch (e) {
    if ((e as NodeJS.ErrnoException).code !== 'ENOENT') throw e;
    existed = false;
  }
  if (existing.includes(GITIGNORE_SENTINEL_HEADER)) {
    return 'unchanged';
  }
  const trimmedEnd = existing.replace(/\s+$/, '');
  const merged =
    trimmedEnd === ''
      ? GITIGNORE_BLOCK + '\n'
      : trimmedEnd + '\n\n' + GITIGNORE_BLOCK + '\n';
  await writeFile(path, merged, 'utf8');
  return existed ? 'appended' : 'created';
}

export const KNOWN_PROVIDERS = [
  'minimal',
  'subscription',
  'openrouter',
  'lmstudio',
  'tracker',
] as const;
export type KnownProvider = (typeof KNOWN_PROVIDERS)[number];

// Maps the user-facing --provider name to the examples/ directory slug.
const PROVIDER_DIR: Record<KnownProvider, string> = {
  minimal: 'minimal',
  subscription: 'with-claude-subscription',
  openrouter: 'with-openrouter',
  lmstudio: 'with-lmstudio',
  tracker: 'with-tracker',
};

function packageRoot(): string {
  // dist/cli/commands/init.js → package root (3 levels up)
  return resolve(dirname(fileURLToPath(import.meta.url)), '..', '..', '..');
}

async function readExampleConfig(provider: KnownProvider): Promise<string> {
  const path = join(packageRoot(), 'examples', PROVIDER_DIR[provider], '.conductor', 'config.yaml');
  return readFile(path, 'utf8');
}

/** Detect a sensible verify_command from project files in cwd. Returns the
 *  detected command, or null if nothing matched. Order matters: more
 *  specific markers first. */
export async function detectVerifyCommand(cwd: string): Promise<string | null> {
  const markers: Array<[string, string]> = [
    ['package.json', 'npm test'],
    ['pyproject.toml', 'pytest'],
    ['setup.py', 'pytest'],
    ['Cargo.toml', 'cargo test'],
    ['go.mod', 'go test ./...'],
    ['Makefile', 'make test'],
  ];
  for (const [marker, cmd] of markers) {
    try {
      await access(join(cwd, marker));
      if (marker === 'pyproject.toml' || marker === 'setup.py') {
        return await detectPythonVerifyCommand(cwd);
      }
      return cmd;
    } catch {
      /* not present, try next */
    }
  }
  return null;
}

/** Detect the right verify_command for a Python project. Caller is expected to
 *  gate the call on `pyproject.toml` or `setup.py` presence. Walks a most-specific
 *  → least-specific cascade and always returns a string (never null):
 *
 *    1. uv.lock          → `uv run pytest`
 *    2. pdm.lock         → `pdm run pytest`
 *    3. poetry.lock      → `poetry run pytest`
 *    4. .venv/<python>   → `<explicit-venv-python> -m pytest`  (platform-split)
 *    5. venv/<python>    → same shape with unprefixed `venv/`
 *    6. fallback         → `python -m pytest`   ← runInit treats this exact
 *                                                 literal as the
 *                                                 `verifyCommandFallback`
 *                                                 discriminator
 *
 *  `platform` is the test seam: defaults to `process.platform` at runtime.
 *  The existence check uses `node:path.join` (host-platform aware) so a test
 *  can seed the file with the host's separator and `access()` finds it
 *  regardless of which `platform` argument was passed. The RETURNED command
 *  string uses an explicit `sep` derived from `platform`, so unit tests can
 *  deterministically assert win32 and posix output on either runner. */
export async function detectPythonVerifyCommand(
  cwd: string,
  platform: NodeJS.Platform = process.platform,
): Promise<string> {
  const lockfiles: Array<[string, string]> = [
    ['uv.lock', 'uv run pytest'],
    ['pdm.lock', 'pdm run pytest'],
    ['poetry.lock', 'poetry run pytest'],
  ];
  for (const [lockfile, cmd] of lockfiles) {
    try {
      await access(join(cwd, lockfile));
      return cmd;
    } catch {
      /* not present, try next */
    }
  }
  const scriptsOrBin = platform === 'win32' ? 'Scripts' : 'bin';
  const pythonExe = platform === 'win32' ? 'python.exe' : 'python';
  const sep = platform === 'win32' ? '\\' : '/';
  for (const dir of ['.venv', 'venv']) {
    try {
      await access(join(cwd, dir, scriptsOrBin, pythonExe));
      return `${dir}${sep}${scriptsOrBin}${sep}${pythonExe} -m pytest`;
    } catch {
      /* not present, try next */
    }
  }
  return 'python -m pytest';
}

function applyVerifyCommand(config: string, command: string): string {
  // Match the verify_command line at the top level of the YAML. The example
  // configs all have it on its own line; this regex is anchored to BOL.
  if (/^verify_command:/m.test(config)) {
    return config.replace(/^verify_command:.*$/m, `verify_command: ${command}`);
  }
  // No existing line — append at end with a leading newline if needed.
  return `${config}${config.endsWith('\n') ? '' : '\n'}verify_command: ${command}\n`;
}

export interface InitArgs {
  cwd: string;
  /** When set, install the matching examples/with-<name>/ config. */
  provider?: KnownProvider;
  /** When false, skip the project-type sniff for verify_command. Default true. */
  detectVerify?: boolean;
}

export interface InitResult {
  configWritten: boolean;
  configSource: 'embedded-default' | KnownProvider;
  verifyCommand: string | null;
  /** True only when `verifyCommand` is the bare `python -m pytest` fallback
   *  (rung 6 of `detectPythonVerifyCommand`'s ladder) — the daemon's shell
   *  must already have `python` on PATH and pytest installed in that Python
   *  for verify to work. Drives the stdout note printed by `attachInit`'s
   *  action callback so the user knows they're on the least-specific branch.
   *  False for any other branch (Node, Rust, Go, Makefile, uv/pdm/poetry,
   *  .venv, venv) or when detection was skipped. */
  verifyCommandFallback: boolean;
  gitignore: 'created' | 'appended' | 'unchanged';
}

export async function runInit(args: InitArgs): Promise<InitResult> {
  const root = join(args.cwd, '.conductor');
  await mkdir(root, { recursive: true });
  for (const sub of SUBDIRS) {
    await mkdir(join(root, sub), { recursive: true });
  }

  const detectVerify = args.detectVerify !== false;
  const verifyCmd = detectVerify ? await detectVerifyCommand(args.cwd) : null;

  let config: string;
  let source: 'embedded-default' | KnownProvider;
  if (args.provider) {
    config = await readExampleConfig(args.provider);
    source = args.provider;
  } else {
    config = DEFAULT_CONFIG;
    source = 'embedded-default';
  }
  if (verifyCmd) {
    config = applyVerifyCommand(config, verifyCmd);
  }

  const configPath = join(root, 'config.yaml');
  const configWritten = await writeIfMissing(configPath, config);

  await writeIfMissing(join(root, 'state.md'), DEFAULT_STATE);
  await writeIfMissing(join(root, 'ordering.md'), DEFAULT_ORDERING);
  await writeIfMissing(join(root, 'journal.md'), DEFAULT_JOURNAL);

  const gitignore = await ensureGitignoreBlock(args.cwd);

  const verifyCommandFallback = verifyCmd === 'python -m pytest';

  return { configWritten, configSource: source, verifyCommand: verifyCmd, verifyCommandFallback, gitignore };
}

async function writeIfMissing(path: string, content: string): Promise<boolean> {
  try {
    await access(path);
    return false;
  } catch {
    /* not present — write it */
  }
  await writeFile(path, content, 'utf8');
  return true;
}

export function attachInit(program: Command): void {
  program
    .command('init')
    .description('Initialize Conductor in the current repo (.conductor/ layout + defaults)')
    .option(
      '--provider <name>',
      `install an example config instead of the embedded default. Recognized: ${KNOWN_PROVIDERS.join(', ')}`,
    )
    .option('--no-detect-verify', 'skip the project-type sniff for verify_command (keep the example default)')
    .action(async (opts: { provider?: string; detectVerify?: boolean }) => {
      let provider: KnownProvider | undefined;
      if (opts.provider) {
        if (!(KNOWN_PROVIDERS as readonly string[]).includes(opts.provider)) {
          // eslint-disable-next-line no-console
          console.error(
            `Unknown --provider "${opts.provider}". Recognized: ${KNOWN_PROVIDERS.join(', ')}`,
          );
          process.exitCode = 1;
          return;
        }
        provider = opts.provider as KnownProvider;
      }
      const result = await runInit({
        cwd: process.cwd(),
        provider,
        detectVerify: opts.detectVerify,
      });
      const firstLine = result.configWritten
        ? `Conductor initialized. .conductor/ scaffold ready (config source: ${result.configSource}${result.verifyCommand ? `, verify_command: ${result.verifyCommand}` : ''}).`
        : `Conductor scaffold present; .conductor/config.yaml left untouched.`;
      const gitignoreLine =
        result.gitignore === 'created'
          ? ' Wrote .gitignore with Conductor runtime-artifact entries.'
          : result.gitignore === 'appended'
            ? ' Appended Conductor runtime-artifact entries to .gitignore.'
            : '';
      // eslint-disable-next-line no-console
      console.log(firstLine + gitignoreLine);
      if (result.verifyCommandFallback) {
        // eslint-disable-next-line no-console
        console.log(
          'Note: No Python venv detected (no .venv/, venv/, uv.lock, pdm.lock, or poetry.lock). Using "python -m pytest" as verify_command. Edit .conductor/config.yaml if pytest isn\'t on the system Python\'s PATH.',
        );
      }
    });
}
